### ISSUE TITLE
state relation to official IEEE templates

### ISSUE THREAD

**Issue by VladimirAlexiev** [dfolio/quarto-ieee#1]
Thanks for this extremely useful extension!
Could you please state its relation to the official IEEE templates:
- https://www.ieee.org/conferences/publishing/templates.html
- https://template-selector.ieee.org/secure/templateSelector/publicationType, in particular https://template-selector.ieee.org/secure/templateSelector/downloadTemplate?publicationTypeId=3&titleId=1&articleId=1&fileId=540
- https://www.overleaf.com/gallery/tagged/ieee-official
- https://www.overleaf.com/latex/templates/ieee-conference-template/grfzhhncsfqn

I mean to state:
- when and where you got the files from, so I can assess the freshness of your extension.
- whether it works for both journals and conferences (seems it does)

I'm comparing your extension to https://github.com/gael-close/ieeetran for submitting to a conference, and it seems yours is the one I need.

Cheers!

**Comment by dfolio** [comment]
Thx for your comments
With IEEE and overleaf you have to write your paper directly in LaTeX, not in Markdown format.
So it is not very convenient to add this template to their site. But, I can try to add this template to the quarto gallery.

**Comment by dfolio** [comment]
`quarto-ieee` is now referenced by quarto-journal: https://quarto.org/docs/extensions/listing-journals.html

**Comment by VladimirAlexiev** [comment]
Hi @dfolio ! I don't mean to list your extension on Overleaf!
I mean that you should state in the README which Latex files is your extension based on, and which version of these files.

Thanks and have a great new year's!
